name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  models: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: genaiscript-${{ runner.os }}-${{ hashFiles('.genaiscript/cache/**') }}
      - name: generate missing documentation
        uses: ./
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue: ${{ github.event.pull_request.number }}
