name: Generate Comments
on:
  workflow_dispatch:
permissions:
  contents: read
  models: read
  pull-requests: write
jobs:
  generate-comments:
    runs-on: ubuntu-latest
    steps:
      # Cache the generated model requests made by GenAIScript
      #
      # A new cache is created for each run to ensure that the latest model requests are used,
      # but previous caches can be restored and reused if availble.
      - uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: genaiscript-${{ github.run_id }}
          restore-keys: |
            genaiscript-
      - uses: actions/checkout@v4
      - name: generate missing comments
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Create a pull request with the changes
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
            title: "Update documentation"
            body: "This pull request contains the latest recommended updates to comments."
            branch: "genai-commentor/update-comments"
            base: main
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Auto-generated comments"
